const fs = require('fs');

const input = [
  {
    "Produce": "Apples",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Apricots",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Blueberries",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Cherries",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Crabapples",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Cranberries",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Currants",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Gooseberries",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Grapes",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Muskmelon",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Nectarines",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Peaches",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Pears",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Plums",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Raspberries",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Rhubarb",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Strawberries (Field)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Strawberries (Greenhouse)",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Watermelon",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Artichoke",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Asian Vegetables",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Asparagus",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "May",
    "Jun": "Jun",
    "Jul": "",
    "Aug": "",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Beans (Green/Yellow)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Beets",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Bitter Melon/Fuzzy Squash",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Bok Choy",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Broccoli",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Brussels Sprouts",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Cabbage",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Carrots",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Cauliflower",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Celery",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Chinese Broccoli (White Flower)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Corn",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Cucumber (Field)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Cucumber (Greenhouse)",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Daikon Radish",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Edible Amaranth (Hinn Choy)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Eggplant",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Garlic",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Leeks",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Lettuce (Assorted)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Lettuce (Greenhouse)",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Mushrooms",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Mustard Greens (Gai Choy)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Napa Cabbage",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Onions (Cooking)",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Onions (Green)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Onions (Red)",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Parsnips",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Peas (Green)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Peas (Snow)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Peppers (Field)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Peppers (Greenhouse)",
    "Jan": "",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Potatoes",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Pumpkin",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Radicchio",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "",
    "Oct": "",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Radishes",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Rapini",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Rutabaga",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Snow Pea Shoots (Dow Miu)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Spinach",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Sprouts",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Squash",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Summer squash",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Sweet potatoes",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Tomatoes (Field)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  },
  {
    "Produce": "Tomatoes (Greenhouse)",
    "Jan": "",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec"
  },
  {
    "Produce": "Water Spinach (Tung Choy)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Yow Choy (Yellow Flower)",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": ""
  },
  {
    "Produce": "Zucchini",
    "Jan": "",
    "Feb": "",
    "Mar": "",
    "Apr": "",
    "May": "",
    "Jun": "",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "",
    "Dec": ""
  }
];

const monthsMap = {
  "Jan": 0,
  "Feb": 1,
  "Mar": 2,
  "Apr": 3,
  "May": 4,
  "Jun": 5,
  "Jul": 6,
  "Aug": 7,
  "Sep": 8,
  "Oct": 9,
  "Nov": 10,
  "Dec": 11
}

const returnData = input.map((fruit, index) => {
  return {
    produce: fruit.Produce,
    type: index <=18 ? 'fruit' : 'vegetable',
    months: Object.values(fruit)
      .filter(item => (item !== '') && (item !== fruit.Produce))
      .map(month => monthsMap[month])
  }
});
console.log(returnData);

fs.writeFile('ontarioData.json', JSON.stringify(returnData), () => {});